# Generated by Django 6.0.4 on 2026-04-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=120)),
                ('tipo_seguro', models.CharField(choices=[('auto', 'Seguro Auto'), ('residencial', 'Seguro Residencial'), ('vida', 'Seguro de Vida'), ('saude', 'Seguro Saude'), ('viagem', 'Seguro Viagem')], max_length=20)),
                ('mensagem', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotacao',
                'verbose_name_plural': 'Cotacoes',
                'ordering': ['-criado_em'],
            },
        ),
    ]
